name: clock_rebuilder
description: A widget that rebuilds child based on time interval
version: 0.0.1
publish_to: "none"
homepage: https://github.com/RagehAz/clock_rebuilder.git

environment:
  sdk: ">=2.10.5 <3.0.0"
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
